"""Sampled from databricks/databricks-dolly-15k (seed=42, n=100, len in [5, 50] Qwen3 tokens, instruction-only).

Regenerate with: ``uv run python -m bench._make_e2e_prompts``.
"""

PROMPTS: list[str] = [
    'What is Sleet?',
    'What is a sitcom?',
    'What is gRPC?',
    'What is room temperature?',
    'Why are some people vegetarian?',
    'Can you describe Gene expression?',
    'What is a shogi?',
    'What is a pot hole?',
    'Why do humans like dogs?',
    'What is Edison famous for?',
    'What are the biggest cloud providers',
    'What is a mammal?',
    'What is the video game Diablo',
    'Why do people drink coffee?',
    'How do you fry shrimp?',
    'what is the Algeria independence date',
    'What happens when you meditate?',
    'When did Massachusetts become a state?',
    'Give me 5 facts about Singapore',
    'How does Windows Fast Startup Work?',
    'Name some of the best overall philosophical books',
    'How to have an evergreen garden?',
    'Why is Football a popular spectator sport?',
    'Who is the patron saint of traveling?',
    'What are the 4 oceans on earth',
    'What are the official languages of Canada?',
    'What is the main cause of snow?',
    'What is the difference between affect and effect?',
    'What are popular street foods from Maharashtra in India',
    "What's the best place to visit China?",
    'What are some ways to care for a new tree',
    'Where do we find Asiatic lions in India?',
    'Who is the greatest soccer player of all time?',
    'Why is there an Irish pub everywhere you go?',
    'What are the words of House Swygert?',
    'Provide a bulleted list of ways to spend less money',
    'How many U.S. presidents were born in Virginia.',
    'On what date was the country of Belize granted independence?',
    'Name some NHL hockey players that were born in Arizona.',
    'Who were the "Big Four" of Grunge?',
    'Is it safe to drink water out of a creek?',
    'What do colleges consider as part of their admissions process?',
    'What is the difference between a day on Earth and Mars?',
    'Why is pricing important in the overall strategy of a product?',
    'What are some unique and interesting travel destinations in the UK?',
    'Does my data need to fit in memory to use Spark?',
    'What are some movies about Artificial Intelligence and Machine Consciousness?',
    'Give me the list of all French president during the fifth Republic',
    'Give me a list of herbs I can plant in my garden',
    'What are some of the best science fiction movies of all time?',
    'Identify which car manufacturer is German or American: Dodge, Volkswagen',
    'What are some ways that an enterprise software company can cut costs?',
    'Which is a species of fish? Sardine or Sardinia',
    'What are considered some of the hippest cities in the United States?',
    'What are the differences between Data Lakehouse vs Data Warehouse vs Data lake',
    'What does the 57 on Heinz ketchup bottles mean?',
    'Give me a list of the 10 best European cities to visit',
    'Classify each of these mammals as either marsupial or placental',
    'Which is an imperial or a metric measurement: inch, millimetres',
    'What are some ways I could commute in to my office in downtown?',
    'As a child, what singer held the longest note ever on Star Search?',
    'Give me a list of the best books to read for new real estate investors',
    'How does one get accepted into a United States federal academy like West Point.',
    'Identify which instrument is string or percussion: Rototom, Mugni',
    'Identify which instrument is string or woodwind: Goje, Dizi',
    "Who are the last 7 soccer fifa men's world cup winners?",
    'How many episodes of the second season of Game of Thrones did Alan Taylor direct?',
    'What are the different types of fees that are charged in the US National Park?',
    'what method of commuting works best to get from Marin County to downtown San Francisco?',
    'What are the names of some of the cities in the Boston Metro West area?',
    'Is Lake Tahoe a beautiful place for vacation/cabin rentals to immerse into nature?',
    'Why is the green card process so long and complex for people from India and China?',
    'Is learning piano on a keyboard just as effective as learning on a grand/upright piano?',
    'Identify which instrument is string or percussion: Tombak, Cizhonghlu',
    'Give me a list of 10 different SciFi movies and which year they were released',
    'What helped Argentina win the World Cup, considering they were not the strongest team on paper?',
    'Which of the following country belongs to Asia and North America? China, Canada, Pakistan, Mexico',
    'What are the top five things to do on a weekend trip to New York City in the winter?',
    'Choose the word which is different from the rest:  Sketch, Diagram, Poster, Chart, Paper',
    'Who are some students at Hogwarts in Ravenclaw house that were in the same year as Harry Potter?',
    'Which one of these do not belong to the group:  House, Cottage, School, Palace, Hut',
    'Some families get rid of TVs and smartphones for the proper growth of children, but are those things desirable?',
    'When will George R.R. Martin release the sixth book in the series "A Song of Ice and Fire"?',
    "When I ski my legs form an A-frame shape and it doesn't look very nice, how can I fix this?",
    'Tell me which one does not fit with the group:  Cigar, Cigarette, Tobacco, Pipe, Hookah',
    'Is there a correlation between the milestones required between Data AI/ML and Intelligent Automation (RPA) value curve over time?',
    'Classify each of the following as either a city or a country:  Seoul, Shanghai, Sao Paolo, Singapore, Sweden.',
    'Categorize the days of the week between weekdays and weekend.\nSunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
    'Which of these are different types of renewable energy resources? Geothermal, Hydro, Machine, Solar, Star, Wind, biomass.',
    'Which of these are brands for clothing: Ford, Samsung, H&M, Tommy Hilfiger, Jack & Jones, Kingfisher',
    'Classify each of the following as a streaming service or cable channel: Netflix, Hulu, Disney+, QVC, ABC, Comedy Central',
    'If you were falling from an airplane and your parachute failed, list some things that you could try to increase your odds of surviving the fall.',
    'Give me the list of top 10 movies released in the current millennium, by IMDB rating. Format: Title (Release Date) Rating',
    'Classify each of the following workouts as upper body or lower body: bench press, pull-up, squat, rows, leg extension, calf raise',
    'Tell me whether these people are DJs or singers: David Guetta, Avicii, Rihanna, Beyonce, Martin Garrix, Calvin Harris, Taylor Swift',
    "I'm sorting my fresh food into two groups. Which are fruits and which are vegetables? Apple, spinach, banana broccoli, potato, plum, pear, avocado and peach.",
    'Classify the following as either an insect or a dog breed: mosquito, Labrador retriever, German shepherd, ant, Siberian husky, poodle, and ladybug.',
    'Write a press release declaring the availability of IronChef, a cooking robot that can create various dishes in 5 cuisines. Be sure to mention some of its advanced technological features.',
    "Which of the following are bait for fishing and which are candy: live worms, gummy worms, lollipops, Hershey's kisses, crickets, and leeches.",
    'Which of the following are not noble gases: helium, sodium, neon, oxygen, argon, hydrogen, calcium, magnesium, lithium, boron, krypton, nitrogen, xenon, aluminium, radon.',
]
